# Generated by Django 4.1 on 2022-08-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=5)),
                ('account_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_code', models.CharField(max_length=2)),
                ('annual_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campany_code', models.CharField(max_length=5)),
                ('campany_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumptionTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_tax_code', models.CharField(max_length=2)),
                ('consumption_tax_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DebitCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_credit_code', models.CharField(max_length=1)),
                ('debit_credit_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=5)),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('je_number', models.CharField(max_length=8)),
                ('je_row_number', models.CharField(max_length=5)),
                ('je_annual', models.CharField(max_length=5)),
                ('je_accounting_date', models.DateTimeField()),
                ('je_entry_date', models.DateTimeField(auto_now_add=True)),
                ('je_type', models.CharField(max_length=1)),
                ('je_account', models.CharField(max_length=5)),
                ('je_subaccount', models.CharField(max_length=5)),
                ('je_consumptiontax', models.CharField(max_length=2)),
                ('je_department', models.CharField(max_length=5)),
                ('je_amount', models.IntegerField(max_length=12)),
                ('je_company', models.CharField(max_length=5)),
                ('je_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JournalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_type_code', models.CharField(max_length=1)),
                ('journal_type_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subaccount_code', models.CharField(max_length=5)),
                ('subaccount_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=5)),
                ('user_name', models.CharField(max_length=20)),
                ('user_authority_code', models.CharField(max_length=1)),
                ('user_authority_name', models.CharField(max_length=5)),
            ],
        ),
    ]
