# Generated by Django 4.1 on 2022-08-22 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_journal_je_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='je_type',
            new_name='je_entry_type',
        ),
    ]
