# Generated by Django 4.1 on 2022-08-25 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journal_je_debit_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.account')),
            ],
            bases=('journal.account',),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_code',
            field=models.CharField(max_length=5, verbose_name='勘定科目コード'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=20, verbose_name='勘定科目名'),
        ),
        migrations.AlterField(
            model_name='annual',
            name='annual_code',
            field=models.CharField(max_length=2, verbose_name='年度コード'),
        ),
        migrations.AlterField(
            model_name='annual',
            name='annual_name',
            field=models.CharField(max_length=10, verbose_name='年度名'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='campany_code',
            field=models.CharField(max_length=5, verbose_name='得意先コード'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='campany_name',
            field=models.CharField(max_length=50, verbose_name='得意先名'),
        ),
        migrations.AlterField(
            model_name='consumptiontax',
            name='consumption_tax_code',
            field=models.CharField(max_length=2, verbose_name='消費税区分コード'),
        ),
        migrations.AlterField(
            model_name='consumptiontax',
            name='consumption_tax_name',
            field=models.CharField(max_length=10, verbose_name='消費税区分名'),
        ),
        migrations.AlterField(
            model_name='debitcredit',
            name='debit_credit_code',
            field=models.CharField(max_length=1, verbose_name='貸借区分コード'),
        ),
        migrations.AlterField(
            model_name='debitcredit',
            name='debit_credit_name',
            field=models.CharField(max_length=2, verbose_name='貸借区分名'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.CharField(max_length=5, verbose_name='部門コード'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=20, verbose_name='部門名'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_account',
            field=models.CharField(max_length=5, verbose_name='勘定科目コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_accounting_date',
            field=models.DateTimeField(verbose_name='計上年月日'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_amount',
            field=models.IntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_annual',
            field=models.CharField(max_length=5, verbose_name='年度コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_company',
            field=models.CharField(max_length=5, verbose_name='取引先コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_consumptiontax',
            field=models.CharField(max_length=2, verbose_name='消費税区分'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_debit_credit',
            field=models.CharField(max_length=1, verbose_name='貸借区分'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_department',
            field=models.CharField(max_length=5, verbose_name='計上部門コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_description',
            field=models.CharField(max_length=100, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_entry_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入力年月日'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_entry_type',
            field=models.CharField(max_length=1, verbose_name='計上区分'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_number',
            field=models.CharField(max_length=8, verbose_name='仕訳番号'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_row_number',
            field=models.CharField(max_length=5, verbose_name='仕訳行番号'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_subaccount',
            field=models.CharField(max_length=5, verbose_name='補助科目コード'),
        ),
        migrations.AlterField(
            model_name='journaltype',
            name='journal_type_code',
            field=models.CharField(max_length=1, verbose_name='計上区分コード'),
        ),
        migrations.AlterField(
            model_name='journaltype',
            name='journal_type_name',
            field=models.CharField(max_length=3, verbose_name='計上区分名'),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='subaccount_code',
            field=models.CharField(max_length=5, verbose_name='補助科目コード'),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='subaccount_name',
            field=models.CharField(max_length=20, verbose_name='補助科目名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_authority_code',
            field=models.CharField(max_length=1, verbose_name='権限コード'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_authority_name',
            field=models.CharField(max_length=5, verbose_name='権限名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_code',
            field=models.CharField(max_length=5, verbose_name='ユーザーコード'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='ユーザー名'),
        ),
    ]
