# Generated by Django 4.1 on 2022-08-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_trialbalance_alter_account_account_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=5, verbose_name='勘定科目コード')),
                ('beginning_balance', models.IntegerField(verbose_name='開始残高')),
            ],
        ),
        migrations.DeleteModel(
            name='TrialBalance',
        ),
    ]
