# Generated by Django 4.1 on 2022-08-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_beginningbalance_delete_trialbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_code',
            field=models.IntegerField(verbose_name='勘定科目コード'),
        ),
        migrations.AlterField(
            model_name='annual',
            name='annual_code',
            field=models.IntegerField(verbose_name='年度コード'),
        ),
        migrations.AlterField(
            model_name='beginningbalance',
            name='account_code',
            field=models.IntegerField(verbose_name='勘定科目コード'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='campany_code',
            field=models.IntegerField(verbose_name='得意先コード'),
        ),
        migrations.AlterField(
            model_name='consumptiontax',
            name='consumption_tax_code',
            field=models.IntegerField(verbose_name='消費税区分コード'),
        ),
        migrations.AlterField(
            model_name='debitcredit',
            name='debit_credit_code',
            field=models.IntegerField(verbose_name='貸借区分コード'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.IntegerField(verbose_name='部門コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_account',
            field=models.IntegerField(verbose_name='勘定科目コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_annual',
            field=models.IntegerField(verbose_name='年度コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_company',
            field=models.IntegerField(verbose_name='取引先コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_consumptiontax',
            field=models.IntegerField(verbose_name='消費税区分'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_debit_credit',
            field=models.IntegerField(verbose_name='貸借区分'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_department',
            field=models.IntegerField(verbose_name='計上部門コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_entry_type',
            field=models.IntegerField(verbose_name='計上区分'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_number',
            field=models.IntegerField(verbose_name='仕訳番号'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_row_number',
            field=models.IntegerField(verbose_name='仕訳行番号'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_subaccount',
            field=models.IntegerField(verbose_name='補助科目コード'),
        ),
        migrations.AlterField(
            model_name='journaltype',
            name='journal_type_code',
            field=models.IntegerField(verbose_name='計上区分コード'),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='subaccount_code',
            field=models.IntegerField(verbose_name='補助科目コード'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_authority_code',
            field=models.IntegerField(verbose_name='権限コード'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_code',
            field=models.IntegerField(verbose_name='ユーザーコード'),
        ),
    ]
