# Generated by Django 4.1 on 2022-09-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='je_company',
            field=models.IntegerField(blank=True, verbose_name='取引先コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_department',
            field=models.IntegerField(blank=True, verbose_name='計上部門コード'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='je_subaccount',
            field=models.IntegerField(blank=True, verbose_name='補助科目コード'),
        ),
    ]
